language: generic
jobs:
  include:
    - stage: build and push docker image
      script:
        - env
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker push -C 1
      env:
        - DOCKER_USERNAME=runyontr
        - secure: wEZ5iEFRnQ4Vzgv50JtttMrgI9aqo/7Krq6zkLEBTWKjXPWvldGS3pwaKTi01zZ0064JWsa+cvDwQcYrAMfy4cIcnGwajdGGzp2zidFWQaQEvz5D8YPD5UAal4JLwF9FN2MUBNwDRfmd6wKuKd+E+GsC0g1aAni0RkHsjvqb7eFeWVk9XbLkhUvsMsW3MdI9JVIaseQC/97s43mIOBAjypXPYBlnlsGr+1a+VASTE/Ieh81sGH42+A6bx9j+teg0P1PrmFd1uTpfcDdv0Zwp2ppeuGjgrBwg+Oyn5lAFxLLljj7nj2BIeD51ixy3vsKt2/Z1VQRNjOzk9NnVaPBMPZUxfBZc/aHi4/sBEnHjW2JHgpADsK2GY0TLSYiXPXRAml4tZs4ogjF6yNb8ZA//IAN0Kw32SBKbkWggKY+hcqppWPsbHJB4dvleE8CwE+vXMd4hMEtE18qzKvuabLDnD+cZuQmGlBdtugBdbZEjMevRD+nGDRoFGE5k9bYixoVhQSjmyTCJ0BG356dLeeXOsOIgKzpS+S+QpjJle5khFJO486YNxL+zcRec/x2hywVq9IDWx5tpY96TBzjvD/Qcr6KjmJYVf7000xbX5aVL0aAUONQoCJ0VjMAsAW2x6qrbctJA6io8GXJfZNeo3lInBIiPH9KiC0f0gXyRnvn/nKY=
    - stage: deploy new image
      script:
        - kubectl apply -f 2/ || true
