language: generic
jobs:
  include:
    - stage: build and push docker image
      script:
        - env
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker push -C 1
    - stage: deploy new image
      script:
        - kubectl apply -f 2/ || true
env:
  global:
    - secure: iSiu1QV9qdkyxoSyF6uWVU9FcQUjVpwThI74IiqUU1zsWZvBVMQxohOFZ6Dnipq0UAl6LMG6yt3N/gDTdAa+zbI2mO/hJOz4AsjXDSvL4ikQ0cZNUYyP5eecSXrjRV+pEbTH26UbXRU/nWqtWRRE1iqr/DI/CK2qOjuMWmyGZYPy/bV1agJ/N/PfmkTdwAg144LeZHyLcsORJpHsA3RkgSPCVJyMK78yWnX8C5T4Z5gPz/Q7KxfRSdtRILlCmUvrGQO8yZKq2C7MuvK2LFowRSrHDuBE+pmUrGCt0tz3D9dK2ZsQZmVXSeakmgkwF+srUFQjuCBkpgeggHyDk/1nCwJfI4eIvM5So9N7RoT3bNFVUbGoOThOEHzueIWM+erNfsGJGVIMdkCGZbFoeGJrPtU2NsvmecCs0QOlvWlyXkwaetheTdzLE/02rDfOQedjvyOt4hbupRKaivy0oxLZjIdiNEQ0uZlNjOeKc7xFqcc8RWkDQWTwlYg1rtZk5l8hTTby68Lh8wdTZC9pPjhTQBLTSJ2c53JIFohSZ+B020d+EaQBK7OCEa8pY0CoPyiE1Hln3Hun6qaN7j09xKR4vf6L8qnhSUKIjwXziaZu555nlPe8XH5076dfzGQPq7jpJxnXFJiI508Qdvtjf4G1CzTfxraZlz/02GhhUmi8zDE=
    - secure: GjuOZtPYWoi3LWlEsh5JG2sQYZ/9oJLOogfpSgqj0yd10EfIpZDFZ3a04t50Lfdr7qXOUCe8LL6tqkB4S1uOb12leBSLseGKcvib9DDr8DtIIUoWK0+qim0KjRnjKwCu/Jwkyazr0L+TdaWdTAuxXmbR2b5aAdcm58s4A/AYOKearklLQLOKB4bToxIXOQV6hKmesO2wBU/Da+8FNivexFL9H3sQPLrS7OxBrYEoE7HrEBpyCCOSELyce/ia4KSKgxxA8FkoUpX4521XpdCLqBvbUasjrtxTHubOzog4e53hZJvaY7/mKhUHZL/re9U40Gj0ug807Ty0PXFFGRhVUUVFQ4J3JBlM1zvTeQVdUpc7fW2ekkvj5GylvwXJQy65DPSSHBQx+MC6FQOCnGSSJHOf5fZsGLJIpHu8ToeesZJI9eaNDVgv2o1fr3VKdqvMs3xZM4KUVmPL7W5x7uVYfB5kxRGm4y27bwepC+yhmcK2aDHMXvCQmMgQM0pYgJBfwcLoApEhn7bshj4d85V7Y5USy5xtKQLeCvg6qLtpgsY9E0ROFJbUCxZFZmQKk/02LxJpQqk0wb5Q/yUIZ4Ab81zS1Wg+fpSN4SlKx1rDftNhkSis4QxvXbkE2ZzY5EmzGYlTbZXRkD63aJaFb1s8jxiTznS6n91/GeXBO5TuyuY=
