language: generic
jobs:
  include:
  - stage: build docker image
    script:
    - make docker -C 1
  - stage: push docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make push -C 1
  - stage: deploy new image
    script:
    - kubectl apply -f 2/ || true
env:
  global:
  - secure: iSiu1QV9qdkyxoSyF6uWVU9FcQUjVpwThI74IiqUU1zsWZvBVMQxohOFZ6Dnipq0UAl6LMG6yt3N/gDTdAa+zbI2mO/hJOz4AsjXDSvL4ikQ0cZNUYyP5eecSXrjRV+pEbTH26UbXRU/nWqtWRRE1iqr/DI/CK2qOjuMWmyGZYPy/bV1agJ/N/PfmkTdwAg144LeZHyLcsORJpHsA3RkgSPCVJyMK78yWnX8C5T4Z5gPz/Q7KxfRSdtRILlCmUvrGQO8yZKq2C7MuvK2LFowRSrHDuBE+pmUrGCt0tz3D9dK2ZsQZmVXSeakmgkwF+srUFQjuCBkpgeggHyDk/1nCwJfI4eIvM5So9N7RoT3bNFVUbGoOThOEHzueIWM+erNfsGJGVIMdkCGZbFoeGJrPtU2NsvmecCs0QOlvWlyXkwaetheTdzLE/02rDfOQedjvyOt4hbupRKaivy0oxLZjIdiNEQ0uZlNjOeKc7xFqcc8RWkDQWTwlYg1rtZk5l8hTTby68Lh8wdTZC9pPjhTQBLTSJ2c53JIFohSZ+B020d+EaQBK7OCEa8pY0CoPyiE1Hln3Hun6qaN7j09xKR4vf6L8qnhSUKIjwXziaZu555nlPe8XH5076dfzGQPq7jpJxnXFJiI508Qdvtjf4G1CzTfxraZlz/02GhhUmi8zDE=
  - secure: KQlOH/ArnKQIGaQlr9sOFXyv5pseWpR2Qj6LICapeQn9WZJKYfYP7bi5dBY2e9hje/E0WkGpVN/vnDSqD81xTTLIWie1rbQ4dmI9/u6uPfQ7xcFtHP4qoe69petGI/VXeudrLTbfzVt9i5c5m1JkUQnrX10ibQom9rPZyGIxOMrX/kwcpPgnQf8bnmB5AqyXOLq8oNwCYPfdymcRezN3yXpcJlwLHxFNWahNic5peXxscDRf8AWKT3jP4a+YehFllOgY2Bp7ZQ/EH2N6i4zeXijFIW490h5v6Hr03RGJpqIlL/MtIIkvf9jAwJks2Gv44c1mrCqxgfL7tqoHJanwGvb+aVBqTkRBcUrGEF7bZJejlx5RzZrW9r6+93TR9+mPNxJP3fuWxRtGrtDWQFwoDtw8pyZ+3JXo2sggKdD+a3idY2TQEmx8bU4DH/o9QgX0LwVU6SW0uRJbAzWaGVaIDZzVLMy/HyHG837WTGeZhN15EXyNxiI3nM6yF0I24fx3O5rzFfcj6UhKiM6W9NtqemJDSTatsUdAAyQPNsRPXzGaZZMz7NnuZjyAY20pWckKGw8BysMgYTntn3Ev6zcVhQ9SLvNoYxafLcv1JNuxIQkEvTJneKWsFeuTyNE/ryHaP4H0WU3S8ecORpX/qa52P2BMAu01rxBP9gnwJ1mi6v8=
