language: generic
jobs:
  include:
    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker push -C 1
      env:
        - DOCKER_USERNAME=runyontr
        - secure: R3saXVX9QOeK8WJY87vKk5B4ve03Jleu62DDTdOPOOk3qPjy/bn4OiyiXkfSc1XagqehBAD6q1XbUGUl7u50+UaXkiqXBNT7Xfy5M427AxLI3jJHgG4Q29WgnLe9Hp0b/nbm8xkIFMImRVD6UTIwqmM+fNKYzDa7k2BkFrgzlebd+gOVg6/358zHWV/gyZEKNy8sYaLWlPEH6mI4BUWDZgjRcGlrmhxsoL9gZBhOq6lnPOVJ+1uC1Ld7haH47xQ9PMcobOhGGpEuRI54eonafvubLxGhwQaCpRtvOemXWcHZZuczPaGrFL2Ou8tlK//sh4fBd8t1it4FWmyMe9l7hs6Ubm3/j0EhJuWytLrhAKCUKblKFLXx8qIUaVg7ndXjROO7Xvhw/tXPqH2hVypOR/CgBrd7yc9+97QciSffg7JhbeFneggDiiZGtEzJLFnmnJDCnw581JWfq+Hu5nDAs7o3Sh5VYyouCugmQBVNONLtU69LytqyzTxLhCtj2s+g/IIQDQ2l3uqaeS7+8cyb58XP/CTWqGbSnck0BcB17YPptHEJejYI1+V6rLXPJVQ9QcR1EpUyEAo4V7zlStrSrozFm2/E/hzYQ3f/sCntWk8drzbg2gxqilx0gAdeH6jc4j92rt/gr/zxspfpJz7TmpcWKTBpqZpfTGAZ0wmYKAo=
    - stage: deploy new image
      script:
        - kubectl apply -f 2/ || true
      env:
        - CREDENTIALS=something_real
