language: generic
jobs:
  include:
    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker push -C 1
      env:
        - DOCKER_USERNAME=runyontr
        - secure: MUvjqBuYjkic2ykQPgf8Z2ha4GGJwzXNjT5BhuTpEKp08V9FZaopdK6Hcsj0Hn2ShOtDxW+jVTjpEQiYYjB3DphM1misdJJe2Ym0gn90dODDLihX/7qjjgvqyDGqV6u8GOtc8yTyFnE3HovLIfHl/sdXI5MZVqGm0NlN7zQZ63NOZZJCmadupbAAjQ6GYf0WtPvkmjpXZDWcQ74UZot96jT9UmA6rV8+ViKT/Zdax6zgi+MMoriq2ozDXC1P0fVKe3Q2kucFC4FuuS4D3q5nVNyHNbNfFkCdWkCDCraremSvHoGlsVGWC/8Hbqmvzj8lQv+0ciYDVtOTQ2l4l6Wwkwdt5DuVk8pKl06XClVU6zJ3joAvkLBCLsycWRSB/AKqTopg0fUa5aDdHrxERo7q2pSrOGRXKiU4z4ehVAZjKb6FNTErzFNLH6bvlxg9jLr6+v1HfHZkBnSg3pUCTNcptEnIE+5dxUSwSTCcJe+5dH3BX2UHMMOG+oFZIW4IT+CgvKybQRoOKhLteSISJ4kqzj1ZOtE8TKLY+14kP55zI/F+/aLdLO/gQdYPafMuLp7jXUuMwU/GYMpGTtqVvxznoY5b/rO/GI1dm9XFw//A6SLNedyyaQwOT2FF2ax2FsnsvwAWNu5ZqwIOAMWDlyNBaoE+r6VRQKB67LelyMbgTZ0=
    - stage: deploy new image
      script:
        - kubectl apply -f 2/ || true
      env:
        - CREDENTIALS=something_real
