language: generic
jobs:
  include:
    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker push -C 1
      env:
        - DOCKER_USERNAME=runyontr
        - secure: nXFF6zeD0JMDbSIFZcsr+HESn862h+4ebWiCfFD3aNBMT0od6z1zJrhRY7UGTHjHB5CKnVsTBCZSl8dUD2jpV2i+aQoDVw6zC27jle8ymjFCnfSyJNLPxSVIhR5rE9wOA7NQNGEDodTsZVWGU2oCknL7wTNxYnaRiAkOoBmWgWQhsuI33a+8pfLRJeQVF76EyQzQ5uzkli8VDVwVo3HFEnR/azFiqs1s5MsSRZSDqr958x5chhLT7Eh0kvf1/67G7o11IcG4nMC9z0gwbncCwqB/gyipmXsNGlMoAFIVOsJR3VWyl6J+mNe1wNWZuX3BI6sOmSRjI2kE+7bx6FlzNRMG1QrAfNfbUpLI1JU26lCOeMvuyEM1638pRYH93Dj5txloBpsXfm5zet7+rC4P0cGkVlBrIFT/HONNNDodZ0v/YGH1gXkxt8gg9Qp68GF/gpFAScA2BVKmRWmW7/wzLWu+dfQ8z+QlVTxlwB5HTd8zgWDIgjhZfqsd+t51WwITeYFpQOkhRJp/UFgs+CttZGao1dkE8vIYnh/KfGXP5UNjMQZKMFln3fiJnvKATwBJFwnu7Xw2FVDh3pqmm87ZJ2KNc7s4fDhEmbvE0OIEPNMv0adWKawRCMB4mawt5WuRqV7O7KwXcnhlzq+Ji3meq6ZWsl4N7b5nbRGeboke43A=
    - stage: deploy new image
      script:
        - kubectl apply -f 2/ || true
