dist: trusty
language: minimal
jobs:
  include:
    - stage: build docker image
      script:
        - make docker -C 1
    - stage: push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make push -C 1
