# resource https://medium.com/@baddour/setting-up-a-litecoin-full-node-a-complete-step-by-step-recipe-that-anyone-can-follow-fb18b82d5cfe
# 2 GB ram (minimum)
# 25 GB PVC
apiVersion: v1
kind: Service
metadata:
  name: litecoind
  labels:
    app.kubernetes.io/name: litecoind
    app.kubernetes.io/version: "0.17.1"
    app.kubernetes.io/component: coin
    app.kubernetes.io/part-of: coin
    app.kubernetes.io/managed-by: raw-yaml
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: litecoind
    app.kubernetes.io/version: "0.17.1"
    app.kubernetes.io/component: coin
    app.kubernetes.io/part-of: coin
    app.kubernetes.io/managed-by: raw-yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoind
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
  labels:
    app.kubernetes.io/name: litecoind
    app.kubernetes.io/version: "0.17.1"
    app.kubernetes.io/component: coin
    app.kubernetes.io/part-of: coin
    app.kubernetes.io/managed-by: raw-yaml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: litecoind
      app.kubernetes.io/version: "0.17.1"
      app.kubernetes.io/component: coin
      app.kubernetes.io/part-of: coin
      app.kubernetes.io/managed-by: raw-yaml
  serviceName: "litecoind"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litecoind
        app.kubernetes.io/version: "0.17.1"
        app.kubernetes.io/component: coin
        app.kubernetes.io/part-of: coin
        app.kubernetes.io/managed-by: raw-yaml
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: litecoind
          image: runyonsolutions/litecoind:0.17.1
          resources:
            requests:
              cpu: "1000m"
              memory: "4Gi"
            limits:
              cpu: "1000"
              memory: "4Gi"
          volumeMounts:
            - name: data
              mountPath: /data/litecoind
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi
